on:
  push:
    branches:
      - main
    paths: &paths
      - "config/*.keymap"
      - "config/*.dtsi"
      - "zephyr/**"
      - "build.yaml"
  pull_request_target:
    branches:
      - main
    paths: *paths
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
